apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-deploy
spec:
  replicas: 10
  template:
   metadata:
    labels:
     app: sample-app
   spec:
    containers:
    - name: sample-pod
      image: nginx
      ports:
      - containerPort: 80
