apiVersion: v1
kind: Service
metadata:
 name: sample-svc
 labels:
  app: sample-app
spec:
 type: LoadBalancer
 ports:
  - port: 80
#    nodePort: 8080
    protocol: TCP
 selector:
   app: sample-app

